---
- hosts: all
  connection: httpapi
  gather_facts: no
  vars:
    login: ansible
    scp_pass: Password123
    server_ip: 192.168.1.238
    # Warning Password with special characters is not supported
    directory_backup: /home/ansible
    ansible_connection: network_cli
    date: "{{ lookup('pipe', 'date +%Y-%m-%d%H-%M-%S') }}"

  collections:
    - dellemc.enterprise_sonic

  tasks:
  - name: Copy Run to Start
    sonic_command:
      commands: "copy running-config startup-config"
    register: result
  - debug: var=result

  - name: Backup Config File
    sonic_command:
      commands: "copy running-config scp://{{ login }}:{{ scp_pass }}@{{ server_ip }}{{ directory_backup }}/{{ inventory_hostname }}-{{ date }}.cfg"
    register: result
  - debug: var=result
